package com.offer18.sdk.constant;

public enum Param {
    CONVERSION_OFFER_ID,
    CONVERSION_ACCOUNT_ID,
    CONVERSION_COUPON,
    CONVERSION_EVENT,
    CONVERSION_SALE,
    CONVERSION_CURRENCY,
    CONVERSION_PAYOUT,
    CONVERSION_ADV_SUB1,
    CONVERSION_ADV_SUB2,
    CONVERSION_ADV_SUB3,
    CONVERSION_ADV_SUB4,
    CONVERSION_ADV_SUB5,
    CONVERSION_POSTBACK_TYPE,
    CONVERSION_IS_GLOBAL_PIXEL,
    CONVERSION_ALLOW_MULTI_CONVERSION,
}
